In [1]:
import pandas as pd
import numpy as np 
import random 

data_frame = pd.read_csv('amazon_reviews.txt', delimiter="\t")
train_data_init = data_frame['REVIEW_TEXT'].values.tolist()
train_labels_init = data_frame['LABEL'].values.tolist()

#shuffling the dataset
shuffle = list(zip(train_data_init, train_labels_init))
random.shuffle(shuffle)
train_data_init, train_labels_init =zip(*shuffle)
del data_frame

final_train_data = np.asarray(train_data_init).tolist()
final_train_labels = np.asarray(train_labels_init).tolist()

#print(final_train_labels)

for i in range(0,len(final_train_labels)):
    if(final_train_labels[i]=="__label1__"):
        final_train_labels[i]=0
    else:
        final_train_labels[i]=1

#print(final_train_labels)
print('Total training reviews ', len(final_train_data))
print('Total training labels ', len(final_train_labels))

Total training reviews  21000
Total training labels  21000


In [2]:
import nltk
sets =set()
maxx = 0
for reviews in final_train_data:
    words = nltk.tokenize.word_tokenize(reviews)
    for word in words:
        sets.add(word)
    if maxx<len(words):
        maxx= len(words)
        
print(maxx)

3340


In [3]:
len(sets)
nltk.download('punkt')
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.utils import to_categorical
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /home/abinash/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/abinash/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Using TensorFlow backend.


In [4]:
MAX_DICT_WORDS = 55000
MAX_SEQ_LENGTH = 3500
EMBEDDING_DIM = 300
tokenizer = Tokenizer(num_words=MAX_DICT_WORDS, filters ='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~')

def tokenize_data(texts, labels):
    tokenizer.fit_on_texts(texts)
    stop = stopwords.words('english')
    tokens = [token for token in texts if token not in stop]
    word_index = tokenizer.word_index
    print('The no of unique tokens is '+ str(len(word_index)))
    lmtzr = WordNetLemmatizer()
    tokens = [lmtzr.lemmatize(word) for word in tokens]
    sequences = tokenizer.texts_to_sequences(tokens)
    data = pad_sequences(sequences, maxlen = MAX_SEQ_LENGTH)
    labels = to_categorical(labels, num_classes=len(set(labels)))
    

    return data, labels, word_index



In [6]:
print(final_train_labels)


[1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 

In [5]:
X, Y, word_index = tokenize_data(final_train_data, final_train_labels)
print(Y)

The no of unique tokens is 36600
[[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [6]:
train_data = X[:int(len(X)*0.9)]
train_labels = Y[:int(len(X)*0.9)]
test_data = X[int(len(X)*0.9):int(len(X)*0.95)]
test_labels = Y[int(len(X)*0.9):int(len(X)*0.95)]
valid_data = X[int(len(X)*0.95):]
valid_labels = Y[int(len(X)*0.95):]

In [8]:
def load_embeddings(word_index, embeddingsfile='glove.6B/glove.6B.%id.txt' %EMBEDDING_DIM):
    embedding_index = {}
    f = open(embeddingsfile, 'r', encoding='utf-8')
    for line in f:
        values = line.split(' ')
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = coefs

    f.close()


    print('Found %s word vectors ' % len(embedding_index))


    embedding_matrix = np.zeros((len(word_index)+1, EMBEDDING_DIM))
    for word, i in word_index.items():
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            # words not found will all be zeros
            embedding_matrix[i]=embedding_vector


    
    embedding_layer = Embedding(len(word_index)+1,
                        EMBEDDING_DIM,
                        weights=[embedding_matrix],
                        input_length =MAX_SEQ_LENGTH,
                        trainable=False)
    
    return embedding_layer

In [9]:
embedding_layer = load_embeddings(word_index)

Found 400000 word vectors 


In [10]:
from keras import Sequential, Model, Input
from keras.layers import Conv1D, MaxPooling1D, AveragePooling1D, Flatten, Dense, GlobalAveragePooling1D, Dropout,LSTM, LSTM, RNN, SimpleRNN, Conv2D, GlobalMaxPooling1D
from keras import callbacks


In [11]:
def cnn_model(sequence_input, embedded_sequences, classes=2):
    x = Conv1D(64, 5, activation='relu')(embedded_sequences)
    x = MaxPooling1D(5)(x)
    x = Conv1D(128, 3, activation='relu')(x)
    x = MaxPooling1D(5)(x)
    x = Conv1D(256, 2, activation='relu')(x)
    x = GlobalAveragePooling1D()(x)
    x = Dense(2048, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)
    preds = Dense(classes, activation='softmax')(x)

    model = Model(sequence_input, preds)
    return model


In [12]:
sequence_input = Input(shape=(MAX_SEQ_LENGTH,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)

model = cnn_model(sequence_input, embedded_sequences, classes=2)
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 3500)              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 3500, 300)         10980300  
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 3496, 64)          96064     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 699, 64)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 697, 128)          24704     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 139, 128)          0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 138, 256)          65792     
__________

In [9]:
from keras.callbacks import ModelCheckpoint, History
filepath="model-{epoch:02d}-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])
history = model.fit(train_data, train_labels,
          validation_data=(valid_data, valid_labels),
          epochs=15, batch_size=128,callbacks=callbacks_list)


In [5]:
from keras.models import load_model

In [8]:
classifier = load_model('model-15-0.67.hdf5')
classifier.layers.pop()
classifier.layers.pop()
classifier.layers.pop()
classifier.layers.pop()
classifier.layers.pop()

new_output =classifier.layers[-1].output
model =Model(classifier.input,new_output)

In [9]:
model.summary()
    

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 3500)              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 3500, 300)         10980300  
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 3496, 64)          96064     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 699, 64)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 697, 128)          24704     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 139, 128)          0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 138, 256)          65792     
__________

In [10]:
model.save('feature_extract.hdf5')

In [39]:
from keras.models import model_from_json
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [7]:
from keras.models import load_model
model = load_model('feature_extract.hdf5')
X=model.predict(train_data)
print(X.shape)


/home/abinash/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


(18900, 256)


In [8]:
print(X.shape)
print(train_labels.shape)
train_labels=train_labels[:,0]

(18900, 256)
(18900, 2)


In [9]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(X, train_labels)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [10]:
X_test =model.predict(test_data)

In [11]:
pred=clf.predict(X_test)
test_labels=test_labels[:,0]

In [12]:
pred

array([0., 0., 0., ..., 0., 0., 1.], dtype=float32)

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(pred, test_labels))

0.6952380952380952


from sklearn import svm

oc_svm_clf = svm.OneClassSVM()

oc_svm_clf.fit(X)

In [24]:
from sklearn import svm

oc_svm_clf = svm.OneClassSVM()

oc_svm_clf.fit(X)


/home/abinash/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma='auto_deprecated',
      kernel='rbf', max_iter=-1, nu=0.5, random_state=None, shrinking=True,
      tol=0.001, verbose=False)

In [28]:
y_pred = oc_svm_clf.predict(X)

In [30]:
for i in range(0,len(y_pred)):
    if(y_pred[i]<0):
        y_pred[i]=0

In [31]:
y_pred

array([1, 1, 1, ..., 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, test_labels))

0.22380952380952382


In [16]:
y_test = model.predict(test_data)

In [14]:
import pickle
pickle.dump(clf, open('abinash.pkl','wb'))

In [14]:
import pickle
with open('abinash.pkl','rb') as file:
    clf=pickle.load(file)

In [17]:
pred=clf.predict(y_test)

In [33]:
test_labels=test_labels[:,0]
#0 is fake and 1 is real
print(test_labels.shape)
print(pred.shape)

(1050,)
(1050,)


In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels,y_pred))

[[254 280]
 [269 247]]
